tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "stripe/stripe-cli"

cask_args appdir: "~/Applications"

cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "jetbrains-toolbox"
cask "obsidian"
cask "raycast"
cask "spotify"
cask "signal"
cask "slack"

brew "giflib"
brew "libpng"
brew "libpq"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "bash"
brew "bat"
brew "bottom"
brew "pkg-config"
brew "htop"
brew "hub"
brew "imagemagick"
brew "jpeg", link: true
brew "jq"
brew "llvm"
brew "lsd"
brew "macvim"
brew "mas"
brew "neovim"
brew "overmind"
brew "postgresql@15"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "stow"
brew "telnet"
brew "tldr"
brew "tree"
brew "z"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "stripe/stripe-cli/stripe"
cask "1password-cli"
cask "docker", args: { appdir: "/Applications" }
cask "fig"
cask "jetbrains-toolbox"
cask "1password"
cask "dropbox"
cask "rectangle"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
mas "Be Focused", id: 973134470
